# Generated by Django 6.0 on 2026-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_distances'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureSports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_range', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Expert', 'Expert')], max_length=50)),
                ('best_season', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'adventure_sports',
            },
        ),
    ]
