# Generated by Django 6.0 on 2026-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_adventuresports'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(max_length=20)),
                ('travels_name', models.CharField(max_length=100)),
                ('departure_place', models.CharField(max_length=50)),
                ('arrival_place', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('fare', models.CharField(max_length=20)),
                ('seat_number', models.CharField(blank=True, default='', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booked_tickets_table',
            },
        ),
    ]
